name: Mirror Repository to GitLab, Azure, and Bitbucket

on:
  push:
    branches:
      - master
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #
      # --- Mirror to GitLab ---
      #
      - name: Mirror to GitLab
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/vbanks.softcloud/terraform-basics-backup.git"
          git push gitlab --all
          git push gitlab --tags
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      #
      # --- Mirror to Azure DevOps ---
      #
      - name: Mirror to Azure DevOps
        run: |
          git remote add azure "https://${AZURE_USER}:${AZURE_PAT}@dev.azure.com/REALORG/REALPROJECT/_git/REALREPO"
          git push azure --all
          git push azure --tags
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PAT:  ${{ secrets.AZURE_PAT }}


      #
      # --- Mirror to Bitbucket ---
      #
      - name: Mirror to Bitbucket
        run: |
          git remote add bitbucket "https://${BITBUCKET_USER}:${BITBUCKET_PAT}@bitbucket.org/vbanks-softcloud/terraform-basics-backup.git"
          git push bitbucket --all
          git push bitbucket --tags
        env:
          BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
          BITBUCKET_PAT:  ${{ secrets.BITBUCKET_PAT }}
